name: Deploy test branch to pages

on:
  push:
    branches:
      - test/**

permissions:
  contents: write

concurrency:
  group: "deploy"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: repo
          token: ${{ secrets.PAT }}
      - name: Copy
        run: |
          cd $GITHUB_WORKSPACE
          mkdir tmp
          cp -r repo -T tmp
          rm -rf tmp/.git
          cd repo
          BRANCH=$(git branch --show-current)
          TARGET_DIRNAME=$(echo $BRANCH | sed 's/^test\///' | sed 's/\//-/')
          git remote update
          git checkout pages
          mkdir $TARGET_DIRNAME
          cd ..
          cp -rf tmp/* -t repo/$TARGET_DIRNAME
          cd repo
          git add .
          git config --global user.name 'Demkitomated'
          git config --global user.email 'auto@mate'
          git commit -m "published ${{ github.sha }}"
          git push
