name: Deploy master to pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

concurrency:
  group: "deploy"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: repo
          token: ${{ secrets.PAT }}
      - name: Copy
        run: |
          cd $GITHUB_WORKSPACE
          mkdir tmp
          cp -r repo -T tmp
          rm -rf tmp/.git
          cd repo
          git remote update
          git checkout pages
          cd ..
          cp -rf tmp/* -t repo
          cd repo
          git add .
          git config --global user.name 'Demkitomated'
          git config --global user.email 'auto@mate'
          git commit -m "automated publish ${{ github.sha }}"
          git push
